// GENERATED by scripts/build_brochure.py -- do not edit by hand.
// Add or change a brochure by re-running the script, or by editing the
// matching public/brochures/<id>/meta.json and running --regen-only.
export const BROCHURES = {
  "caraway-st": {
    id: "caraway-st",
    title: "Caraway ST Tire",
    basePath: "/brochures/caraway-st",
    pages: 4,
    ext: "webp",
    pdfUrl: "/brochures/caraway-st/source.pdf",
    imagesUrl: "/brochures/caraway-st/images.json",
    logos: [
      {
        label: "Caraway",
        svg: "/brochures/caraway-st/images/_logo/CARAWAY LOGO SVG.svg",
        png: "/brochures/caraway-st/images/_logo/CARAWAY LOGO PNG.png",
      },
    ],
  },
  "hemisphere-plt": {
    id: "hemisphere-plt",
    title: "Hemisphere Passenger & Light Truck",
    basePath: "/brochures/hemisphere-plt",
    pages: 14,
    ext: "webp",
    pdfUrl: "/brochures/hemisphere-plt/source.pdf",
    imagesUrl: "/brochures/hemisphere-plt/images.json",
    logos: [
      {
        label: "Hemisphere",
        svg: "/brochures/hemisphere-plt/images/_logo/HEMISPHERE LOGO SVG.svg",
        png: "/brochures/hemisphere-plt/images/_logo/HEMISPHERE LOGO PNG.png",
      },
    ],
  },
  "hirun-atvutv": {
    id: "hirun-atvutv",
    title: "HI-RUN ATV & UTV Tire",
    basePath: "/brochures/hirun-atvutv",
    pages: 24,
    ext: "webp",
    pdfUrl: "/brochures/hirun-atvutv/source.pdf",
    imagesUrl: "/brochures/hirun-atvutv/images.json",
    logos: [
      {
        label: "HI-RUN",
        svg: "/brochures/hirun-st/images/_logo/HI-RUN LOGO SVG.svg",
        png: "/brochures/hirun-st/images/_logo/HI-RUN LOGO PNG.png",
      },
      {
        label: "WolfPack",
        svg: "/brochures/wolfpack-atvutv/images/_logo/WOLF PACK LOGO SVG.svg",
        png: "/brochures/wolfpack-atvutv/images/_logo/WOLF PACK LOGO PNG.png",
      },
    ],
  },
  "hirun-specialty": {
    id: "hirun-specialty",
    title: "HI-RUN Specialty Tire",
    basePath: "/brochures/hirun-specialty",
    pages: 44,
    ext: "webp",
    pdfUrl: "/brochures/hirun-specialty/source.pdf",
    imagesUrl: "/brochures/hirun-specialty/images.json",
    logos: [
      {
        label: "HI-RUN",
        svg: "/brochures/hirun-st/images/_logo/HI-RUN LOGO SVG.svg",
        png: "/brochures/hirun-st/images/_logo/HI-RUN LOGO PNG.png",
      },
    ],
  },
  "hirun-st": {
    id: "hirun-st",
    title: "HI-RUN ST Tire",
    basePath: "/brochures/hirun-st",
    pages: 4,
    ext: "webp",
    pdfUrl: "/brochures/hirun-st/source.pdf",
    imagesUrl: "/brochures/hirun-st/images.json",
    logos: [
      {
        label: "HI-RUN",
        svg: "/brochures/hirun-st/images/_logo/HI-RUN LOGO SVG.svg",
        png: "/brochures/hirun-st/images/_logo/HI-RUN LOGO PNG.png",
      },
    ],
  },
  "hirun-tube": {
    id: "hirun-tube",
    title: "HI-RUN Tube Application Guide",
    basePath: "/brochures/hirun-tube",
    pages: 2,
    ext: "webp",
    pdfUrl: "/brochures/hirun-tube/source.pdf",
    logos: [
      {
        label: "HI-RUN",
        svg: "/brochures/hirun-st/images/_logo/HI-RUN LOGO SVG.svg",
        png: "/brochures/hirun-st/images/_logo/HI-RUN LOGO PNG.png",
      },
    ],
  },
  "longmarch-mtr": {
    id: "longmarch-mtr",
    title: "Long March MTR",
    basePath: "/brochures/longmarch-mtr",
    pages: 16,
    ext: "webp",
    pdfUrl: "/brochures/longmarch-mtr/source.pdf",
    imagesUrl: "/brochures/longmarch-mtr/images.json",
    logos: [
      {
        label: "Long March",
        svg: "/brochures/longmarch-mtr/images/_logo/LONGMARCH LOGO SVG.svg",
        png: "/brochures/longmarch-mtr/images/_logo/LONGMARCH LOGO PNG.png",
      },
    ],
  },
  "roadone-mtr": {
    id: "roadone-mtr",
    title: "RoadOne MTR",
    basePath: "/brochures/roadone-mtr",
    pages: 24,
    ext: "webp",
    pdfUrl: "/brochures/roadone-mtr/source.pdf",
    imagesUrl: "/brochures/roadone-mtr/images.json",
    logos: [
      {
        label: "RoadOne",
        svg: "/brochures/roadone-mtr/images/_logo/ROADONE LOGO SVG.svg",
        png: "/brochures/roadone-mtr/images/_logo/ROADONE LOGO PNG.png",
      },
    ],
  },
  "roadone-plt": {
    id: "roadone-plt",
    title: "RoadOne Passenger & Light Truck",
    basePath: "/brochures/roadone-plt",
    pages: 21,
    ext: "webp",
    pdfUrl: "/brochures/roadone-plt/source.pdf",
    imagesUrl: "/brochures/roadone-plt/images.json",
    logos: [
      {
        label: "RoadOne",
        svg: "/brochures/roadone-mtr/images/_logo/ROADONE LOGO SVG.svg",
        png: "/brochures/roadone-mtr/images/_logo/ROADONE LOGO PNG.png",
      },
    ],
  },
  "supercargo-mtr": {
    id: "supercargo-mtr",
    title: "SuperCargo MTR",
    basePath: "/brochures/supercargo-mtr",
    pages: 15,
    ext: "webp",
    pdfUrl: "/brochures/supercargo-mtr/source.pdf",
    imagesUrl: "/brochures/supercargo-mtr/images.json",
    logos: [
      {
        label: "SuperCargo",
        svg: "/brochures/supercargo-str/images/_logo/SUPERCARGO LOGO SVG.svg",
        png: "/brochures/supercargo-str/images/_logo/SUPERCARGO LOGO PNG.png",
      },
    ],
  },
  "supercargo-str": {
    id: "supercargo-str",
    title: "SuperCargo STR",
    basePath: "/brochures/supercargo-str",
    pages: 3,
    ext: "webp",
    pdfUrl: "/brochures/supercargo-str/source.pdf",
    imagesUrl: "/brochures/supercargo-str/images.json",
    logos: [
      {
        label: "SuperCargo",
        svg: "/brochures/supercargo-str/images/_logo/SUPERCARGO LOGO SVG.svg",
        png: "/brochures/supercargo-str/images/_logo/SUPERCARGO LOGO PNG.png",
      },
    ],
  },
  "synergy-mtr": {
    id: "synergy-mtr",
    title: "Synergy MTR",
    basePath: "/brochures/synergy-mtr",
    pages: 14,
    ext: "webp",
    pdfUrl: "/brochures/synergy-mtr/source.pdf",
    imagesUrl: "/brochures/synergy-mtr/images.json",
    logos: [
      {
        label: "Synergy",
        svg: "/brochures/synergy-str/images/_logo/SYNERGY LOGO SVG.svg",
        png: "/brochures/synergy-str/images/_logo/SYNERGY LOGO PNG.png",
      },
    ],
  },
  "synergy-str": {
    id: "synergy-str",
    title: "Synergy STR",
    basePath: "/brochures/synergy-str",
    pages: 4,
    ext: "webp",
    pdfUrl: "/brochures/synergy-str/source.pdf",
    imagesUrl: "/brochures/synergy-str/images.json",
    logos: [
      {
        label: "Synergy",
        svg: "/brochures/synergy-str/images/_logo/SYNERGY LOGO SVG.svg",
        png: "/brochures/synergy-str/images/_logo/SYNERGY LOGO PNG.png",
      },
    ],
  },
  "wolfpack-atvutv": {
    id: "wolfpack-atvutv",
    title: "WolfPack ATV / UTV",
    basePath: "/brochures/wolfpack-atvutv",
    pages: 19,
    ext: "webp",
    pdfUrl: "/brochures/wolfpack-atvutv/source.pdf",
    imagesUrl: "/brochures/wolfpack-atvutv/images.json",
    logos: [
      {
        label: "WolfPack",
        svg: "/brochures/wolfpack-atvutv/images/_logo/WOLF PACK LOGO SVG.svg",
        png: "/brochures/wolfpack-atvutv/images/_logo/WOLF PACK LOGO PNG.png",
      },
    ],
  },
};

export const getBrochure = (id) => BROCHURES[id];
