"""Turn a source PDF into a self-hosted flipbook brochure.

Renders every page to WebP, copies the PDF alongside it for download, records a
meta.json, then regenerates the React registry from every meta.json on disk.

    python scripts/build_brochure.py _inbox/WolfPackATVUTV.pdf \
        --id wolfpack-atvutv --title "WolfPack ATV / UTV"

Re-run with --regen-only after hand-editing a meta.json to refresh the registry
without re-rendering anything.

Requires PyMuPDF and Pillow.
"""

import argparse
import io
import json
import shutil
import sys
from pathlib import Path

import fitz  # PyMuPDF
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BROCHURE_DIR = ROOT / "public" / "brochures"
REGISTRY = ROOT / "src" / "components" / "config" / "brochures.js"

# 144 dpi renders a US Letter page to 1224x1584 -- sharp enough to read type at
# full-screen on a retina laptop without pushing pages past ~150 KB.
DPI = 144
QUALITY = 80


def render(pdf_path, out_dir, dpi, quality):
    doc = fitz.open(pdf_path)
    zoom = dpi / 72
    matrix = fitz.Matrix(zoom, zoom)

    for old in out_dir.glob("page-*.webp"):
        old.unlink()

    total = 0
    for i, page in enumerate(doc, start=1):
        pix = page.get_pixmap(matrix=matrix, alpha=False)
        img = Image.open(io.BytesIO(pix.tobytes("ppm")))
        dest = out_dir / f"page-{i:02d}.webp"
        img.save(dest, "WEBP", quality=quality, method=6)
        size = dest.stat().st_size
        total += size
        print(f"  page-{i:02d}.webp  {img.width}x{img.height}  {size // 1024} KB")

    print(f"  {doc.page_count} pages, {total / 1024 / 1024:.1f} MB total")
    return doc.page_count


def js_string(value):
    return json.dumps(value, ensure_ascii=False)


def regenerate_registry():
    """Rebuild brochures.js from every public/brochures/*/meta.json."""
    entries = []
    for meta_path in sorted(BROCHURE_DIR.glob("*/meta.json")):
        entries.append(json.loads(meta_path.read_text(encoding="utf-8")))

    lines = [
        "// GENERATED by scripts/build_brochure.py -- do not edit by hand.",
        "// Add or change a brochure by re-running the script, or by editing the",
        "// matching public/brochures/<id>/meta.json and running --regen-only.",
        "export const BROCHURES = {",
    ]
    for e in entries:
        base = f"/brochures/{e['id']}"
        lines.append(f"  {js_string(e['id'])}: {{")
        lines.append(f"    id: {js_string(e['id'])},")
        lines.append(f"    title: {js_string(e['title'])},")
        lines.append(f"    basePath: {js_string(base)},")
        lines.append(f"    pages: {e['pages']},")
        lines.append('    ext: "webp",')
        if e.get("pdf"):
            lines.append(f"    pdfUrl: {js_string(base + '/source.pdf')},")
        if e.get("logo"):
            logo = e["logo"]
            lines.append("    logo: {")
            lines.append(f"      label: {js_string(logo['label'])},")
            for fmt in ("svg", "png"):
                if logo.get(fmt):
                    lines.append(f"      {fmt}: {js_string(logo[fmt])},")
            lines.append("    },")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("export const getBrochure = (id) => BROCHURES[id];")
    lines.append("")

    REGISTRY.write_text("\n".join(lines), encoding="utf-8")
    print(f"registry: {len(entries)} brochure(s) -> {REGISTRY.relative_to(ROOT)}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pdf", nargs="?", help="source PDF, e.g. _inbox/Foo.pdf")
    parser.add_argument("--id", help="url slug, e.g. wolfpack-atvutv")
    parser.add_argument("--title", help="display title")
    parser.add_argument("--dpi", type=int, default=DPI)
    parser.add_argument("--quality", type=int, default=QUALITY)
    parser.add_argument(
        "--no-pdf",
        action="store_true",
        help="render pages but do not publish the source PDF for download",
    )
    parser.add_argument(
        "--regen-only",
        action="store_true",
        help="only rebuild brochures.js from existing meta.json files",
    )
    args = parser.parse_args()

    if args.regen_only:
        regenerate_registry()
        return

    if not (args.pdf and args.id and args.title):
        parser.error("pdf, --id and --title are required unless --regen-only")

    pdf_path = Path(args.pdf)
    if not pdf_path.is_file():
        sys.exit(f"no such PDF: {pdf_path}")

    out_dir = BROCHURE_DIR / args.id
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"{args.id}: {pdf_path.name}")

    pages = render(pdf_path, out_dir, args.dpi, args.quality)

    meta_path = out_dir / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.is_file() else {}
    meta.update({"id": args.id, "title": args.title, "pages": pages})

    if args.no_pdf:
        meta["pdf"] = False
        (out_dir / "source.pdf").unlink(missing_ok=True)
    else:
        shutil.copyfile(pdf_path, out_dir / "source.pdf")
        meta["pdf"] = True

    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    regenerate_registry()


if __name__ == "__main__":
    main()
